---@class fk.DrawInitialCards: TriggerEvent
fk.DrawInitialCards = TriggerEvent:subclass("fk.DrawInitialCards")
---@class fk.AfterDrawInitialCards: TriggerEvent
fk.AfterDrawInitialCards = TriggerEvent:subclass("fk.AfterDrawInitialCards")
---@class fk.EventTurnChanging: TriggerEvent
fk.EventTurnChanging = TriggerEvent:subclass("fk.EventTurnChanging")
---@class fk.GameStart: TriggerEvent
fk.GameStart = TriggerEvent:subclass("fk.GameStart")
---@class fk.RoundStart: TriggerEvent
fk.RoundStart = TriggerEvent:subclass("fk.RoundStart")
---@class fk.RoundEnd: TriggerEvent
fk.RoundEnd = TriggerEvent:subclass("fk.RoundEnd")
---@class fk.AfterRoundEnd: TriggerEvent
fk.AfterRoundEnd = TriggerEvent:subclass("fk.AfterRoundEnd")
---@class fk.PreTurnStart: TriggerEvent
fk.PreTurnStart = TriggerEvent:subclass("fk.PreTurnStart")
---@class fk.BeforeTurnStart: TriggerEvent
fk.BeforeTurnStart = TriggerEvent:subclass("fk.BeforeTurnStart")
---@class fk.TurnStart: TriggerEvent
fk.TurnStart = TriggerEvent:subclass("fk.TurnStart")
---@class fk.TurnEnd: TriggerEvent
fk.TurnEnd = TriggerEvent:subclass("fk.TurnEnd")
---@class fk.AfterTurnEnd: TriggerEvent
fk.AfterTurnEnd = TriggerEvent:subclass("fk.AfterTurnEnd")
---@class fk.EventPhaseStart: TriggerEvent
fk.EventPhaseStart = TriggerEvent:subclass("fk.EventPhaseStart")
---@class fk.EventPhaseProceeding: TriggerEvent
fk.EventPhaseProceeding = TriggerEvent:subclass("fk.EventPhaseProceeding")
---@class fk.EventPhaseEnd: TriggerEvent
fk.EventPhaseEnd = TriggerEvent:subclass("fk.EventPhaseEnd")
---@class fk.AfterPhaseEnd: TriggerEvent
fk.AfterPhaseEnd = TriggerEvent:subclass("fk.AfterPhaseEnd")
---@class fk.EventPhaseChanging: TriggerEvent
fk.EventPhaseChanging = TriggerEvent:subclass("fk.EventPhaseChanging")
---@class fk.EventPhaseSkipping: TriggerEvent
fk.EventPhaseSkipping = TriggerEvent:subclass("fk.EventPhaseSkipping")
---@class fk.EventPhaseSkipped: TriggerEvent
fk.EventPhaseSkipped = TriggerEvent:subclass("fk.EventPhaseSkipped")
---@class fk.DrawNCards: TriggerEvent
fk.DrawNCards = TriggerEvent:subclass("fk.DrawNCards")
---@class fk.AfterDrawNCards: TriggerEvent
fk.AfterDrawNCards = TriggerEvent:subclass("fk.AfterDrawNCards")
---@class fk.StartPlayCard: TriggerEvent
fk.StartPlayCard = TriggerEvent:subclass("fk.StartPlayCard")
