---@class fk.BeforePropertyChange: TriggerEvent
fk.BeforePropertyChange = TriggerEvent:subclass("fk.BeforePropertyChange")
---@class fk.PropertyChange: TriggerEvent
fk.PropertyChange = TriggerEvent:subclass("fk.PropertyChange")
---@class fk.AfterPropertyChange: TriggerEvent
fk.AfterPropertyChange = TriggerEvent:subclass("fk.AfterPropertyChange")
---@class fk.BeforeTurnOver: TriggerEvent
fk.BeforeTurnOver = TriggerEvent:subclass("fk.BeforeTurnOver")
---@class fk.TurnedOver: TriggerEvent
fk.TurnedOver = TriggerEvent:subclass("fk.TurnedOver")
---@class fk.BeforeChainStateChange: TriggerEvent
fk.BeforeChainStateChange = TriggerEvent:subclass("fk.BeforeChainStateChange")
---@class fk.ChainStateChanged: TriggerEvent
fk.ChainStateChanged = TriggerEvent:subclass("fk.ChainStateChanged")
---@class fk.AfterDrawPileShuffle: TriggerEvent
fk.AfterDrawPileShuffle = TriggerEvent:subclass("fk.AfterDrawPileShuffle")
---@class fk.BeforeTriggerSkillUse: TriggerEvent
fk.BeforeTriggerSkillUse = TriggerEvent:subclass("fk.BeforeTriggerSkillUse")
---@class fk.CardShown: TriggerEvent
fk.CardShown = TriggerEvent:subclass("fk.CardShown")
---@class fk.AreaAborted: TriggerEvent
fk.AreaAborted = TriggerEvent:subclass("fk.AreaAborted")
---@class fk.AreaResumed: TriggerEvent
fk.AreaResumed = TriggerEvent:subclass("fk.AreaResumed")
---@class fk.GeneralShown: TriggerEvent
fk.GeneralShown = TriggerEvent:subclass("fk.GeneralShown")
---@class fk.GeneralRevealed: TriggerEvent
fk.GeneralRevealed = TriggerEvent:subclass("fk.GeneralRevealed")
---@class fk.GeneralHidden: TriggerEvent
fk.GeneralHidden = TriggerEvent:subclass("fk.GeneralHidden")
