---@class fk.PreCardUse: TriggerEvent
fk.PreCardUse = TriggerEvent:subclass("fk.PreCardUse")
---@class fk.AfterCardUseDeclared: TriggerEvent
fk.AfterCardUseDeclared = TriggerEvent:subclass("fk.AfterCardUseDeclared")
---@class fk.AfterCardTargetDeclared: TriggerEvent
fk.AfterCardTargetDeclared = TriggerEvent:subclass("fk.AfterCardTargetDeclared")
---@class fk.CardUsing: TriggerEvent
fk.CardUsing = TriggerEvent:subclass("fk.CardUsing")
---@class fk.BeforeCardUseEffect: TriggerEvent
fk.BeforeCardUseEffect = TriggerEvent:subclass("fk.BeforeCardUseEffect")
---@class fk.TargetSpecifying: TriggerEvent
fk.TargetSpecifying = TriggerEvent:subclass("fk.TargetSpecifying")
---@class fk.TargetConfirming: TriggerEvent
fk.TargetConfirming = TriggerEvent:subclass("fk.TargetConfirming")
---@class fk.TargetSpecified: TriggerEvent
fk.TargetSpecified = TriggerEvent:subclass("fk.TargetSpecified")
---@class fk.TargetConfirmed: TriggerEvent
fk.TargetConfirmed = TriggerEvent:subclass("fk.TargetConfirmed")
---@class fk.CardUseFinished: TriggerEvent
fk.CardUseFinished = TriggerEvent:subclass("fk.CardUseFinished")
---@class fk.PreCardRespond: TriggerEvent
fk.PreCardRespond = TriggerEvent:subclass("fk.PreCardRespond")
---@class fk.CardResponding: TriggerEvent
fk.CardResponding = TriggerEvent:subclass("fk.CardResponding")
---@class fk.CardRespondFinished: TriggerEvent
fk.CardRespondFinished = TriggerEvent:subclass("fk.CardRespondFinished")
---@class fk.PreCardEffect: TriggerEvent
fk.PreCardEffect = TriggerEvent:subclass("fk.PreCardEffect")
---@class fk.BeforeCardEffect: TriggerEvent
fk.BeforeCardEffect = TriggerEvent:subclass("fk.BeforeCardEffect")
---@class fk.CardEffecting: TriggerEvent
fk.CardEffecting = TriggerEvent:subclass("fk.CardEffecting")
---@class fk.CardEffectFinished: TriggerEvent
fk.CardEffectFinished = TriggerEvent:subclass("fk.CardEffectFinished")
---@class fk.CardEffectCancelledOut: TriggerEvent
fk.CardEffectCancelledOut = TriggerEvent:subclass("fk.CardEffectCancelledOut")
